### ISSUE TITLE
chat.postMessage fails on large query strings 

### ISSUE THREAD

**Issue by andrewholsted** [FredKSchott/slackey#14]
In `api-client.js` line 73, the request method is hardcoded as `GET` for `chat.postMessage`. This leads to an error when you send a large chat message, i.e. with many attachments. It would be nice to default this to `POST` or allow an optional override. I'll probably be working on a pull request very soon if you have any suggestions

**Comment by FredKSchott** [comment]
:+1: Nice, good catch. iirc, it isn't hardcoded for any specific reason, only because we're doing special logic already and missing the default case where `qs: GET` is normally applied. There should be no problem with changing that to `POST` instead and calling it a day. 

When you make the change, can you include a comment near it in the code explaining this so that no one changes it accidentally?

**Comment by andrewholsted** [comment]
@FredKSchott In regards to these lines

**Comment by FredKSchott** [comment]
@andrewholsted `qs` is the problem you're trying to solve for right? Where the data is getting clipped as it's encoded into the URL query string? If that's the case, then you'll need to use body. But I'm not familiar enough with the API to know off the top of my head so I'd recommend playing around with both and seeing what works.

**Comment by andrewholsted** [comment]
:thumbsup: Will do

**Comment by FredKSchott** [comment]
Fixed by @andrewholstead via #15

**Comment by FredKSchott** [comment]
published to npm under v1.1.1
